language: python
python:
  - 2.7
addons:
  postgresql: "9.4"
script: python manage.py travis-test
after_failure:
  - sudo supervisorctl status
  - sudo cat /var/log/*-wsgi.log
  - sudo cat /var/log/nginx/error.log
