"""empty message

Revision ID: 37f0184a96ef
Revises: None
Create Date: 2014-06-11 12:01:07.842498

"""

# revision identifiers, used by Alembic.
revision = '37f0184a96ef'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=160), nullable=True),
    sa.Column('incarnation', sa.String(length=160), nullable=True),
    sa.Column('object', sa.String(length=160), nullable=True),
    sa.Column('key', sa.String(length=160), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_entity'), 'record', ['entity'], unique=False)
    op.create_index('lookup', 'record', ['entity', 'incarnation', 'object', 'key', 'timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('lookup', table_name='record')
    op.drop_index(op.f('ix_record_entity'), table_name='record')
    op.drop_table('record')
    ### end Alembic commands ###
